In [1]:
arr1 = ['pune',"mumbai",'surat',"kolkata",'bihar',"jaipur",'chennai']

In [2]:
type(arr1)

list

In [3]:
arr1[0]

'pune'

In [2]:
import numpy
arr2 = numpy.array([10,20,30,40,50])

In [5]:
type(arr2)

numpy.ndarray

In [6]:
print(arr2)

[10 20 30 40 50]


In [7]:
arr2

array([10, 20, 30, 40, 50])

In [8]:
arr3 = numpy.array((100,200,300,400,500))

In [9]:
type(arr3)

numpy.ndarray

In [6]:
import numpy as np
a0 = np.array(10)

In [11]:
print(a0)

10


In [12]:
a0.ndim

0

In [13]:
a0

array(10)

In [14]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [15]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
a1.ndim

1

In [17]:
a2 = np.array([[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000]])

In [18]:
a2

array([[   1,    2,    3],
       [  10,   20,   30],
       [ 100,  200,  300],
       [1000, 2000, 3000]])

In [19]:
a2.ndim

2

In [20]:
a3 = np.array([[[1,2,3],[10,20,30]],[[100,200,300],[1000,2000,3000]]])

In [21]:
a3

array([[[   1,    2,    3],
        [  10,   20,   30]],

       [[ 100,  200,  300],
        [1000, 2000, 3000]]])

In [22]:
a3.ndim

3

In [23]:
a4 = np.array([4,44,444,4444], ndmin=4)

In [24]:
a4

array([[[[   4,   44,  444, 4444]]]])

In [25]:
a4.ndim

4

In [41]:
arr2[1]  [10,20,30,40,50]

20

In [43]:
a2[1,2] [[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000]]

30

In [44]:
a2[2,2]

300

In [45]:
a3[0,0,0] [[[1,2,3],[10,20,30]],[[100,200,300],[1000,2000,3000]]]

1

In [55]:
a4[0,0,0,3]

4444

In [56]:
a4[0,0,1,0]

IndexError: index 1 is out of bounds for axis 2 with size 1

In [7]:
a12 = np.array([1,2,3])

In [12]:
a12[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [8]:
arrr = np.array([1,2,3,1,2,3,1,2,3])

In [58]:
arrr

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [59]:
arr2

array([10, 20, 30, 40, 50])

In [60]:
arr2[-1]

50

In [61]:
arr2[-2]

40

In [62]:
arr2[1:]

array([20, 30, 40, 50])

In [63]:
arr2[:3]

array([10, 20, 30])

In [64]:
arr2[:]

array([10, 20, 30, 40, 50])

In [65]:
arr2[1:4:1]

array([20, 30, 40])

In [66]:
arr2[1:4:2]

array([20, 40])

In [67]:
arr2[:4:3]

array([10, 40])

In [68]:
arr2[::4]

array([10, 50])

In [69]:
arr2[::]

array([10, 20, 30, 40, 50])

In [70]:
for i in arr2:
  print(i)

10
20
30
40
50
